/* Ask Havenly — UK property-search copilot. */
(function(){
  const style=document.createElement('style');style.textContent='.ask-havenly{position:fixed;right:22px;bottom:22px;z-index:1000}.ask-toggle{border:0;border-radius:999px;padding:14px 18px;background:#0b1320;color:#fff;font:700 14px DM Sans,sans-serif;box-shadow:0 12px 35px rgba(11,19,32,.22);cursor:pointer}.ask-panel{display:none;position:absolute;right:0;bottom:58px;width:min(430px,calc(100vw - 32px));background:#fff;border:1px solid #e5e7eb;border-radius:18px;box-shadow:0 24px 70px rgba(11,19,32,.18);overflow:hidden}.ask-panel.open{display:block}.ask-head{padding:16px 18px;border-bottom:1px solid #eef0f3}.ask-head strong{display:block;font-size:15px}.ask-head span{font-size:12px;color:#64748b}.ask-suggestions{display:flex;gap:7px;flex-wrap:wrap;padding:10px 16px;border-bottom:1px solid #eef0f3}.ask-suggestion{border:1px solid #dfe4ea;background:#fff;border-radius:999px;padding:7px 9px;font-size:11px;color:#334155;cursor:pointer}.ask-body{padding:16px;height:350px;overflow:auto}.ask-msg{padding:10px 12px;border-radius:12px;margin:0 0 10px;line-height:1.5;font-size:13px}.ask-msg.ai{background:#f4f6f8}.ask-msg.user{background:#0b1320;color:#fff;margin-left:30px}.ask-form{display:flex;gap:8px;padding:12px;border-top:1px solid #eef0f3}.ask-form input{min-width:0;flex:1;border:1px solid #d7dde5;border-radius:10px;padding:11px}.ask-form button{border:0;border-radius:10px;padding:0 14px;background:#0b1320;color:#fff;font-weight:700;cursor:pointer}.ask-form button:disabled{opacity:.55;cursor:wait}.ask-disclaimer{padding:0 16px 12px;color:#94a3b8;font-size:10px}.ask-result{display:block;text-decoration:none;color:inherit;background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:11px;margin-top:8px}.ask-result strong{display:block;font-size:13px}.ask-result small{display:block;color:#64748b;margin-top:3px}.ask-result:hover{border-color:#94a3b8}.ask-meta{margin-top:7px;font-size:10px;color:#64748b}.ask-havenly *{box-sizing:border-box}';document.head.appendChild(style);
  const wrap=document.createElement('div');wrap.className='ask-havenly';wrap.innerHTML='<button class="ask-toggle" type="button" aria-expanded="false">Ask Havenly AI</button><section class="ask-panel" aria-label="Ask Havenly AI"><div class="ask-head"><strong>Ask Havenly</strong><span>Your UK property search copilot</span></div><div class="ask-suggestions"><button class="ask-suggestion" type="button" data-q="3 bedrooms under £500k">3 beds under £500k</button><button class="ask-suggestion" type="button" data-q="2 bedroom apartment in London under £700k">London apartments</button><button class="ask-suggestion" type="button" data-q="4 bedroom detached house with garage">Detached + garage</button></div><div class="ask-body"><div class="ask-msg ai">Hi. Tell me what kind of home you are looking for — location, budget, bedrooms, property type or features. I’ll search Havenly.</div></div><form class="ask-form"><input aria-label="Ask Havenly" autocomplete="off" placeholder="e.g. 3 beds under £450k near Bristol"><button type="submit">Send</button></form><div class="ask-disclaimer">AI guidance is informational and does not replace professional legal, financial or property advice.</div></section>';document.body.appendChild(wrap);
  const toggle=wrap.querySelector('.ask-toggle'),panel=wrap.querySelector('.ask-panel'),body=wrap.querySelector('.ask-body'),form=wrap.querySelector('.ask-form'),input=form.querySelector('input'),send=form.querySelector('button');
  toggle.onclick=()=>{const open=panel.classList.toggle('open');toggle.setAttribute('aria-expanded',open);if(open)input.focus()};
  wrap.querySelectorAll('.ask-suggestion').forEach(b=>b.onclick=()=>{input.value=b.dataset.q;form.requestSubmit()});
  function addMessage(text,kind='ai'){const el=document.createElement('div');el.className='ask-msg '+kind;el.textContent=text;body.appendChild(el);body.scrollTop=body.scrollHeight;return el}
  function addResults(items){(items||[]).slice(0,8).forEach(p=>{const id=p.id||p.property_id;const card=document.createElement('a');card.className='ask-result';card.href=id?`property.html?id=${encodeURIComponent(id)}`:'#';const price=formatPrice(p.price);card.innerHTML=`<strong>${escapeHtml(p.title||'Property')}</strong><small>${escapeHtml(p.location||'')} · ${price} · ${p.bedrooms??'—'} bed · ${p.bathrooms??'—'} bath</small><div class="ask-meta">${escapeHtml(p.property_type||'Home')}${p.tenure?' · '+escapeHtml(p.tenure):''}${p.epc_rating?' · EPC '+escapeHtml(p.epc_rating):''}${p.parking?' · '+escapeHtml(p.parking):''}</div>`;if(!id)card.addEventListener('click',e=>e.preventDefault());body.appendChild(card)});body.scrollTop=body.scrollHeight}
  function formatPrice(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n):'Price on request'}
  function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  form.onsubmit=async e=>{e.preventDefault();const q=input.value.trim();if(!q||send.disabled)return;addMessage(q,'user');input.value='';send.disabled=true;send.textContent='…';const loading=addMessage('Searching Havenly’s live property catalogue…','ai');try{const r=await fetch('/api/ask-havenly',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,k:8})});const data=await r.json().catch(()=>({}));loading.remove();if(!r.ok)throw new Error(data.error||'Search failed');addMessage(data.message||`I found ${data.properties?.length||0} matching properties.`);addResults(data.properties);if(data.interpreted){const i=data.interpreted;const bits=[];if(i.mode)bits.push(i.mode==='rent'?'Rental search':'For-sale search');if(i.bedrooms)bits.push(`${i.bedrooms}+ beds`);if(i.bathrooms)bits.push(`${i.bathrooms}+ baths`);if(i.maxPrice)bits.push(`up to ${formatPrice(i.maxPrice)}`);if(i.locationWords?.length)bits.push(i.locationWords.slice(0,2).join(', '));if(bits.length)addMessage('Search understood: '+bits.join(' · '));}}catch(err){loading.remove();addMessage(err.message||'I couldn’t complete that search. Please try again.')}finally{send.disabled=false;send.textContent='Send';input.focus()}};
})();
