window.HAVENLY_PROPERTIES = [
{id:1,dbId:'10000000-0000-4000-8000-000000000001',price:475000,title:'3 bedroom semi-detached house',location:'Bristol, BS7',beds:3,baths:2,area:'1,245 sq ft',epc:'B',tenure:'Freehold',council:'Band D',parking:'Driveway',garden:'Rear garden',score:null,tag:'Featured',status:'Featured',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=90'},
{id:2,dbId:'10000000-0000-4000-8000-000000000002',price:625000,title:'2 bedroom apartment',location:'London, SE1',beds:2,baths:2,area:'885 sq ft',epc:'C',tenure:'Leasehold',council:'Band F',parking:'Permit',garden:'Shared',score:null,tag:'City living',status:'New',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=90'},
{id:3,dbId:'10000000-0000-4000-8000-000000000003',price:385000,title:'4 bedroom detached house',location:'Leeds, LS16',beds:4,baths:2,area:'1,890 sq ft',epc:'C',tenure:'Freehold',council:'Band E',parking:'Garage + drive',garden:'Large rear garden',score:null,tag:'Family home',status:'Available',image:'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1600&q=90'},
{id:4,dbId:'10000000-0000-4000-8000-000000000004',price:510000,title:'3 bedroom townhouse',location:'Manchester, M20',beds:3,baths:2,area:'1,430 sq ft',epc:'B',tenure:'Freehold',council:'Band D',parking:'Allocated',garden:'Private garden',score:null,tag:'Garden',status:'Available',image:'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1600&q=90'},
{id:5,dbId:'10000000-0000-4000-8000-000000000005',price:795000,title:'4 bedroom period home',location:'Bath, BA1',beds:4,baths:3,area:'2,240 sq ft',epc:'D',tenure:'Freehold',council:'Band G',parking:'On-street',garden:'Courtyard',score:null,tag:'Period',status:'New',image:'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=90'},
{id:6,dbId:'10000000-0000-4000-8000-000000000006',price:295000,title:'2 bedroom cottage',location:'York, YO31',beds:2,baths:1,area:'925 sq ft',epc:'C',tenure:'Freehold',council:'Band C',parking:'Driveway',garden:'Rear garden',score:null,tag:'Character',status:'Available',image:'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1600&q=90'}
];
(function(){
 const load=src=>new Promise((resolve,reject)=>{if(document.querySelector(`script[src="${src}"]`))return resolve();const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
 async function boot(){try{await load('supabase-client.js?v=20260904-auth');await load('supabase-data.js?v=20260904-auth')}catch(e){return}if(!window.havenlyDataReady)return;const page=location.pathname.split('/').pop();
  if(page==='property.html'){await new Promise(r=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',r,{once:true}):r());try{const id=Number(new URLSearchParams(location.search).get('id'))||1,p=window.HAVENLY_PROPERTIES.find(x=>x.id===id),btn=document.getElementById('saveBtn');if(!p||!btn)return;const user=await window.havenlyData.user();if(user&&p.dbId){const c=await window.havenlyData.client(),check=await c.from('saved_properties').select('property_id').eq('user_id',user.id).eq('property_id',p.dbId).maybeSingle();let isSaved=!!check.data;btn.textContent=isSaved?'Saved ✓':'Save property ♡';btn.onclick=async()=>{btn.disabled=true;try{if(isSaved){await window.havenlyData.unsaveProperty(p);isSaved=false;btn.textContent='Save property ♡'}else{await window.havenlyData.saveProperty(p);isSaved=true;btn.textContent='Saved ✓'}}catch(e){alert('Unable to update your saved homes. Please try again')}finally{btn.disabled=false}}}}catch(e){console.warn('saved sync unavailable',e)}}
  if(page==='property.html'){await new Promise(r=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',r,{once:true}):r());const id=Number(new URLSearchParams(location.search).get('id'))||1;let tries=0;const addSalesLink=()=>{const decision=document.querySelector('a.decision-link');if(!decision||document.getElementById('salesHistoryLink'))return false;const a=document.createElement('a');a.id='salesHistoryLink';a.className='decision-link';a.href=`sales-history.html?id=${id}`;a.innerHTML='<span>View sale history<br><small>HM Land Registry · exact UPRN matches only</small></span><span>→</span>';decision.insertAdjacentElement('afterend',a);return true};const timer=setInterval(()=>{if(addSalesLink()||++tries>20)clearInterval(timer)},250)}
  if(page==='account.html'){await new Promise(r=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',r,{once:true}):r());try{const ids=await window.havenlyData.savedPropertyIds();if(ids&&sessionStorage.getItem('havenlySupabaseAccountSync')!=='1'){sessionStorage.setItem('havenlySupabaseAccountSync','1');localStorage.setItem('havenlySaved',JSON.stringify(ids));location.reload()}}catch(e){}}
  if(page==='enquiry.html'){await new Promise(r=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',r,{once:true}):r());const form=document.getElementById('form');if(!form)return;form.addEventListener('submit',async e=>{const id=Number(new URLSearchParams(location.search).get('id'))||1,p=window.HAVENLY_PROPERTIES.find(x=>x.id===id),u=await window.havenlyData.user();if(!p||!u||!p.dbId)return;e.preventDefault();e.stopImmediatePropagation();const f={name:document.getElementById('name').value.trim(),email:document.getElementById('email').value.trim(),phone:document.getElementById('phone').value.trim(),interest:document.getElementById('interest').value,message:document.getElementById('message').value.trim()},type=new URLSearchParams(location.search).get('type');try{if(type==='viewing'||f.interest==='Arranging a viewing')await window.havenlyData.submitViewing(p,f);else await window.havenlyData.submitEnquiry(p,f,type);form.hidden=true;const r=document.getElementById('result');r.hidden=false;r.innerHTML='<div class="success"><strong>'+((type==='viewing'||f.interest==='Arranging a viewing')?'Viewing request sent.':'Enquiry sent.')+'</strong><p>Your request has been submitted to the Havenly database for this demo.</p><a class="dark-btn" href="account.html">Open your buyer workspace →</a> <a class="outline-btn" href="property.html?id='+p.id+'">Return to property</a></div>'}catch(err){const r=document.getElementById('result');r.hidden=false;r.innerHTML='<div class="error">We could not submit this request. Please try again.</div>';console.error(err)}},true)}
 }boot()})();